# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Tests

on:
  push:
  pull_request:
    branches: [ master ]

jobs:
  #lint:
  #  runs-on: ubuntu-latest
  #  steps:
  #  - uses: actions/checkout@v2
  #  - name: Set up Python 3.8
  #    uses: actions/setup-python@v2
  #    with:
  #      python-version: 3.8
  #  - name: Install dependencies
  #    run: |
  #      python -m pip install --upgrade pip
  #      python -m pip install flake8
  #  - name: Lint with flake8
  #    run: |
  #      flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

  build_and_test_sdist:
    name: Test Wheel Python 3.8
    runs-on: ubuntu-latest
    #needs: [lint]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Upgrade pip 
      run: |
        python -m pip install --upgrade pip wheel
        python -m pip install -r requirements/build.txt
        python -m pip install -r requirements/tests.txt
    - name: Build Wheel
      run: |
        python setup.py bdist_wheel
    - name: Install Wheel
      run: |
        cd dist
        ls -al
        pip install FeLS*.whl -v
    - name: Test Installed Wheel
      run: |
        pwd
        ls -al
        mkdir -p tmpdir
        cd tmpdir
        #xdoctest -m fels
        FELS_INSTALL_DIR=$(python -c "import fels, os; print(os.path.dirname(fels.__file__))")
        echo "FELS_INSTALL_DIR = $FELS_INSTALL_DIR"
        pytest --verbose --xdoctest --cov-report term --cov=fels ../tests $FELS_INSTALL_DIR

    - name: Upload Wheel artifact
      uses: actions/upload-artifact@v2
      with:
        name: wheels
        path: ./dist/*.whl

  build_and_test_sdist_other_os:
    name: Test ${{ matrix.python-version }} on ${{ matrix.os }}, arch=${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    #needs: [lint]
    strategy:
      matrix:
        os: [windows-latest, macOS-latest]
        python-version: 
          - '3.8'
        arch: [auto]

    steps:
    - name: Checkout source
      uses: actions/checkout@v2

    # Configure compilers for Windows 64bit.
    - name: Enable MSVC 64bit
      if: matrix.os == 'windows-latest' && matrix.cibw_build != 'cp3*-win32'
      uses: ilammy/msvc-dev-cmd@v1
    
    # Configure compilers for Windows 32bit.
    - name: Enable MSVC 32bit
      if: matrix.os == 'windows-latest' && matrix.cibw_build == 'cp3*-win32'
      uses: ilammy/msvc-dev-cmd@v1
      with:
        arch: x86

    # Emulate aarch64 ppc64le s390x under linux
    - name: Set up QEMU
      if: runner.os == 'Linux' && matrix.arch != 'auto'
      uses: docker/setup-qemu-action@v1
      with:
        platforms: all

    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Upgrade pip 
      shell: bash
      run: |
        python -m pip install --upgrade pip wheel
        python -m pip install -r requirements/build.txt
        python -m pip install -r requirements/tests.txt
    - name: Build Wheel
      shell: bash
      run: |
        python setup.py bdist_wheel
    - name: Install Wheel
      shell: bash
      run: |
        cd dist
        ls -al
        pip install FeLS*.whl -v
    - name: Test Installed Wheel
      shell: bash
      run: |
        pwd
        ls -al
        mkdir -p tmpdir
        cd tmpdir
        #xdoctest -m fels
        FELS_INSTALL_DIR=$(python -c "import fels, os; print(os.path.dirname(fels.__file__))")
        echo "FELS_INSTALL_DIR = $FELS_INSTALL_DIR"
        pytest --verbose --xdoctest --cov-report term --cov=fels ../tests $FELS_INSTALL_DIR
